# Generated by Django 5.2.6 on 2025-09-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Member',
        ),
    ]
